version: "3.8"
services:
  site:
    build:
      context: site
      # target: dev
    volumes:
      - ./site/index.html:/app/index.html
      - ./site/vite.config.ts:/app/vite.config.ts
      - ./site/tsconfig.json:/app/tsconfig.json
      - ./site/public:/app/public
      - ./site/src:/app/src
    ports:
      - 5173:5173
    depends_on:
      - backend
  backend:
    build:
      context: backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - 3000:3000
